export const CONFIG = {
    VERIFY_ID_LENGTH: 12,
    VERIFY_EXPIRE_SECONDS: 300,
    VERIFIED_EXPIRE_SECONDS: 2592000,
    MEDIA_GROUP_EXPIRE_SECONDS: 60,
    MEDIA_GROUP_DELAY_MS: 3000,
    PENDING_MAX_MESSAGES: 10,
    ADMIN_CACHE_TTL_SECONDS: 300,
    NEEDS_REVERIFY_TTL_SECONDS: 600,
    THREAD_HEALTH_TTL_MS: 60000,
    MESSAGE_MAP_TTL_SECONDS: 86400,
    RATE_LIMIT_MESSAGE: 45,
    RATE_LIMIT_VERIFY: 3,
    RATE_LIMIT_WINDOW: 60,
    BUTTON_COLUMNS: 2,
    MAX_TITLE_LENGTH: 128,
    MAX_NAME_LENGTH: 30,
    API_TIMEOUT_MS: 10000,
    CLEANUP_BATCH_SIZE: 10,
    MAX_CLEANUP_DISPLAY: 20,
    CLEANUP_LOCK_TTL_SECONDS: 1800,
    MAX_RETRY_ATTEMPTS: 3,
    D1_WRITE_MAX_RETRIES: 3,
    D1_WRITE_BASE_DELAY_MS: 120,
    D1_WRITE_MAX_DELAY_MS: 1200,
    USER_LOCK_TTL_MS: 15000,
    USER_LOCK_ACQUIRE_TIMEOUT_MS: 6000,
    USER_LOCK_RETRY_INTERVAL_MS: 120,
    USER_LOCK_HEARTBEAT_INTERVAL_MS: 5000,
    TOPIC_CREATE_VERIFY_MAX_RETRIES: 2,
    TOPIC_CREATE_VERIFY_BACKOFF_MS: 350,
    KEYWORD_MAX_LENGTH: 200,
    KEYWORD_MATCH_MAX_TEXT_LENGTH: 4000
};

export const LOCAL_QUESTIONS = [
    { question: "冰融化后会变成什么？", correct_answer: "水", incorrect_answers: ["石头", "木头", "火"] },
    { question: "正常人有几只眼睛？", correct_answer: "2", incorrect_answers: ["1", "3", "4"] },
    { question: "以下哪个属于水果？", correct_answer: "香蕉", incorrect_answers: ["白菜", "猪肉", "大米"] },
    { question: "1 加 2 等于几？", correct_answer: "3", incorrect_answers: ["2", "4", "5"] },
    { question: "5 减 2 等于几？", correct_answer: "3", incorrect_answers: ["1", "2", "4"] },
    { question: "2 乘以 3 等于几？", correct_answer: "6", incorrect_answers: ["4", "5", "7"] },
    { question: "10 加 5 等于几？", correct_answer: "15", incorrect_answers: ["10", "12", "20"] },
    { question: "8 减 4 等于几？", correct_answer: "4", incorrect_answers: ["2", "3", "5"] },
    { question: "在天上飞的交通工具是什么？", correct_answer: "飞机", incorrect_answers: ["汽车", "轮船", "自行车"] },
    { question: "星期一的后面是星期几？", correct_answer: "星期二", incorrect_answers: ["星期日", "星期五", "星期三"] },
    { question: "鱼通常生活在哪里？", correct_answer: "水里", incorrect_answers: ["树上", "土里", "火里"] },
    { question: "我们用什么器官来听声音？", correct_answer: "耳朵", incorrect_answers: ["眼睛", "鼻子", "嘴巴"] },
    { question: "晴朗的天空通常是什么颜色的？", correct_answer: "蓝色", incorrect_answers: ["绿色", "红色", "紫色"] },
    { question: "太阳从哪个方向升起？", correct_answer: "东方", incorrect_answers: ["西方", "南方", "北方"] },
    { question: "小狗发出的叫声通常是？", correct_answer: "汪汪", incorrect_answers: ["喵喵", "咩咩", "呱呱"] }
];
